services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: History
    ports:
      - 5432:5432
  main:
    build:
      context: ./main
    ports:
      - 80:8501
    depends_on:
      - postgres

  
    